FROM tomcat:9.0-jdk11

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR (rename to ROOT.war if you want / URL)
COPY target/project_3.war /usr/local/tomcat/webapps/ROOT.war

# Expose the port Tomcat will run on inside container
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
