FROM tomcat:9.0-jdk8

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR
COPY target/project_3.war /usr/local/tomcat/webapps/project_3.war

EXPOSE 8080

CMD ["catalina.sh", "run"]
